source 'https://rubygems.org'
# source 'https://rails-assets.org'

gem 'rails', '= 5.2.6'
gem 'bootsnap'
gem 'listen'
gem 'sqlite3'
gem 'sass-rails'
gem 'haml-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'unpoly-rails', path: '../unpoly-rails'
gem 'bower-rails'
gem 'bootstrap', '<5'
gem 'rake'

gem 'tilt'
gem 'sprockets-rails'
gem 'sprockets', '~> 3.0'

gem 'byebug'
gem 'web-console'
gem 'faker'

