source 'https://rubygems.org'
# source 'https://rails-assets.org'

gem 'rails', '4.2.0'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'haml-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'unpoly-rails', path: '../unpoly-rails'
gem 'bower-rails'
gem 'bootstrap'
gem 'rake', '< 11'

gem 'tilt', '=1.4.1'
gem 'sprockets-rails', '~> 3.2.1'
gem 'sprockets', '~> 3.7.2'

gem 'byebug'
gem 'web-console', '~> 2.0'
